import AppKit
import Foundation
import SwiftUI
import WebKit

@MainActor
final class MacMediaBrowserController: ObservableObject {
  let browser = IPadInteractiveMediaBrowser()
  let library = IPadBrowserLibraryStore()

  @Published private(set) var isResolving = false
  @Published private(set) var statusMessage = "ページ内の動画を再生すると、HLS通信を検出します。"
  @Published private(set) var selectedSourceHost = ""

  private var resolutionTask: Task<Void, Never>?
  private var resolutionID: UUID?

  deinit {
    resolutionTask?.cancel()
  }

  func navigate() {
    cancelResolutionForPageChange()
    browser.navigate(browser.addressText)
  }

  func recordSuccessfulVisit(_ visit: IPadInteractiveMediaBrowser.SuccessfulPageVisit?) {
    guard let visit else { return }
    library.recordVisit(url: visit.url, title: visit.title)
  }

  func toggleBookmark() {
    guard let url = browser.currentPublicPageURL else { return }
    let added = library.toggleBookmark(url: url, title: browser.pageTitle)
    statusMessage = added ? "ブックマークへ追加しました。" : "ブックマークから削除しました。"
  }

  func open(_ entry: IPadBrowserLibraryStore.Entry) {
    guard let url = entry.resolvedURL else { return }
    cancelResolutionForPageChange()
    browser.addressText = url.absoluteString
    browser.navigate(url.absoluteString)
  }

  func cancelResolution() {
    resolutionID = nil
    resolutionTask?.cancel()
    resolutionTask = nil
    isResolving = false
    statusMessage = "配信解析を中止しました。"
  }

  func cancelResolutionForPageChange() {
    guard resolutionTask != nil else { return }
    resolutionID = nil
    resolutionTask?.cancel()
    resolutionTask = nil
    isResolving = false
    statusMessage = "ページ移動により配信解析を中止しました。"
  }

  func resolveAndStart(
    player: RealtimePlayerController,
    runner: RestorationRunner,
    onSelectedPlayback: @escaping @MainActor () -> Void
  ) {
    guard !isResolving else { return }
    resolutionTask?.cancel()
    let id = UUID()
    resolutionID = id
    isResolving = true
    statusMessage = "ブラウザで検出した配信候補を確認しています…"
    browser.activateInspection()
    let navigationGeneration = browser.navigationGeneration

    resolutionTask = Task { @MainActor [weak self, weak player, weak runner] in
      guard let self else { return }
      defer {
        if self.resolutionID == id {
          self.resolutionID = nil
          self.isResolving = false
          self.resolutionTask = nil
        }
      }
      guard let player, let runner else { return }
      do {
        // Give the isolated-world observers one quiet turn to publish network
        // responses generated by the user's most recent play-button action.
        try await Task.sleep(nanoseconds: 350_000_000)
        guard self.resolutionIsCurrent(
          id,
          navigationGeneration: navigationGeneration
        ) else { throw CancellationError() }
        let candidates = await self.browser.snapshotCandidates()
        guard self.resolutionIsCurrent(
          id,
          navigationGeneration: navigationGeneration
        ) else { throw CancellationError() }
        guard !candidates.isEmpty else {
          throw IPadWebMediaDiscoveryError.noCandidates
        }
        let source = try await Self.preferredHLS(
          from: candidates,
          progress: { [weak self] text in
            guard let self,
              self.resolutionIsCurrent(
                id,
                navigationGeneration: navigationGeneration
              )
            else { return }
            self.statusMessage = text
          }
        )
        try Task.checkCancellation()
        guard self.resolutionIsCurrent(
          id,
          navigationGeneration: navigationGeneration
        ) else { throw CancellationError() }
        guard source.kind == .hls, source.hlsPlaylist != nil else {
          throw MacMediaBrowserError.hlsRequired
        }
        self.selectedSourceHost =
          source.hlsPlaylist?.url.host ?? source.mediaURL.host ?? ""
        self.statusMessage = source.hlsPlaylist?.isLive == true
          ? "ライブHLSを検出しました。復元再生を開始します。"
          : "HLSを検出しました。区間を連結しながら復元再生します。"
        runner.appendExternalLog(
          "ブラウザ: HLS入力を確認しました（\(self.selectedSourceHost.isEmpty ? "配信元" : self.selectedSourceHost)）\n"
        )
        player.startHLS(source: source, runner: runner)
        onSelectedPlayback()
      } catch is CancellationError {
        if self.resolutionID == id {
          self.statusMessage = "配信解析を中止しました。"
        }
      } catch {
        guard self.resolutionID == id else { return }
        self.statusMessage = error.localizedDescription
        runner.appendExternalLog("ブラウザ解析: \(error.localizedDescription)\n")
      }
    }
  }

  private func resolutionIsCurrent(
    _ id: UUID,
    navigationGeneration: Int
  ) -> Bool {
    resolutionID == id
      && browser.navigationGeneration == navigationGeneration
      && !Task.isCancelled
  }

  private nonisolated static func preferredHLS(
    from candidates: [IPadWebMediaCandidate],
    progress: @escaping @MainActor (String) -> Void
  ) async throws -> IPadResolvedMediaSource {
    var sources: [IPadResolvedMediaSource] = []
    var evidence: [IPadBrowserMediaEvidence?] = []
    var seen = Set<String>()
    var usefulError: Error?

    for candidate in candidates.prefix(
      IPadBrowserMediaSourceSelector.maximumPlayableChoices
    ) {
      try Task.checkCancellation()
      do {
        let source = try await IPadMediaURLResolver().resolve(
          candidate.url.absoluteString,
          policy: resolutionPolicy(for: candidate),
          context: candidate.requestContext
        )
        guard source.kind == .hls,
          let playlist = source.hlsPlaylist,
          !playlist.segments.isEmpty,
          playlist.duration > 0,
          !IPadBrowserMediaSourceSelector.isHighConfidenceAdvertisementSource(source)
        else { continue }

        let key = IPadBrowserMediaSourceSelector.deduplicationKey(for: source)
        guard seen.insert(key).inserted else { continue }
        await progress(
          "HLS候補を確認: \(source.mediaURL.host ?? "配信元") / \(durationLabel(playlist.duration))"
        )
        if IPadBrowserMediaSourceSelector.shouldAcceptImmediately(
          source,
          evidence: candidate.mediaEvidence
        ) {
          return source
        }
        sources.append(source)
        evidence.append(candidate.mediaEvidence)
      } catch is CancellationError {
        throw CancellationError()
      } catch IPadMediaURLResolverError.unsafeInitialURL {
        continue
      } catch {
        usefulError = usefulError ?? error
      }
    }

    guard let index = IPadBrowserMediaSourceSelector.preferredIndex(
      in: sources,
      evidence: evidence
    ) else {
      throw usefulError ?? IPadWebMediaDiscoveryError.noCandidates
    }
    return sources[index]
  }

  private nonisolated static func resolutionPolicy(
    for candidate: IPadWebMediaCandidate
  ) -> IPadMediaURLResolutionPolicy {
    guard candidate.selectionState == .activeCurrentSource,
      let evidence = candidate.mediaEvidence,
      evidence.isPlaying,
      evidence.isVisible,
      evidence.visibilityAttested,
      evidence.renderedArea >= 4_096,
      let origin = browserOrigin(for: candidate.url)
    else { return .publicDiscovered }
    return .visibleBrowserDiscovered(origin)
  }

  private nonisolated static func browserOrigin(for url: URL) -> URL? {
    guard var components = URLComponents(url: url, resolvingAgainstBaseURL: true),
      components.scheme?.lowercased() == "https",
      components.user == nil,
      components.password == nil,
      components.host?.isEmpty == false
    else { return nil }
    components.scheme = "https"
    components.path = ""
    components.query = nil
    components.fragment = nil
    return components.url
  }

  private nonisolated static func durationLabel(_ duration: TimeInterval) -> String {
    guard duration.isFinite, duration >= 0 else { return "長さ不明" }
    let seconds = Int(duration.rounded())
    return String(
      format: "%d:%02d:%02d",
      seconds / 3_600,
      (seconds % 3_600) / 60,
      seconds % 60
    )
  }
}

private enum MacMediaBrowserError: LocalizedError {
  case hlsRequired

  var errorDescription: String? {
    switch self {
    case .hlsRequired:
      "復元再生できるHLS配信を確認できませんでした。ページ内の本編を再生してから、もう一度解析してください。"
    }
  }
}

struct MacMediaBrowserView: View {
  @ObservedObject var controller: MacMediaBrowserController
  @ObservedObject var browser: IPadInteractiveMediaBrowser
  @ObservedObject var player: RealtimePlayerController
  @ObservedObject var runner: RestorationRunner
  let selectPlayback: @MainActor () -> Void

  init(
    controller: MacMediaBrowserController,
    player: RealtimePlayerController,
    runner: RestorationRunner,
    selectPlayback: @escaping @MainActor () -> Void
  ) {
    self.controller = controller
    browser = controller.browser
    self.player = player
    self.runner = runner
    self.selectPlayback = selectPlayback
  }

  var body: some View {
    VStack(spacing: 8) {
      browserToolbar
      HStack(spacing: 10) {
        if browser.isLoading {
          ProgressView().controlSize(.small)
        } else {
          Image(systemName: browser.challengeActive ? "hand.raised.fill" : "globe")
            .foregroundStyle(browser.challengeActive ? .orange : .secondary)
        }
        Text(
          controller.isResolving
            ? controller.statusMessage
            : (browser.statusMessage ?? controller.statusMessage)
        )
          .font(.caption)
          .lineLimit(2)
        Spacer()
        Text("候補 \(browser.candidateCount)件")
          .font(.caption.monospacedDigit())
          .foregroundStyle(.secondary)
        Button {
          controller.resolveAndStart(
            player: player,
            runner: runner,
            onSelectedPlayback: selectPlayback
          )
        } label: {
          Label(
            controller.isResolving ? "解析中" : "HLSを復元再生",
            systemImage: "waveform.path.ecg.rectangle"
          )
        }
        .buttonStyle(.borderedProminent)
        .disabled(
          controller.isResolving || browser.challengeActive
            || browser.isLoading || browser.candidateCount == 0
        )
      }
      .padding(.horizontal, 4)

      HSplitView {
        IPadInteractiveBrowserWebView(browser: browser)
          .id(browser.webViewGeneration)
          .frame(minWidth: 500, minHeight: 430, maxHeight: .infinity)
        candidateList
          .frame(
            minWidth: 250,
            idealWidth: 310,
            maxWidth: 390,
            maxHeight: .infinity
          )
      }
      .frame(maxHeight: .infinity)
    }
    .padding(.vertical, 10)
    .frame(maxHeight: .infinity)
    .onChange(of: browser.successfulPageVisit?.revision) { _, _ in
      controller.recordSuccessfulVisit(browser.successfulPageVisit)
    }
    .onChange(of: browser.navigationGeneration) { _, _ in
      controller.cancelResolutionForPageChange()
    }
  }

  private var browserToolbar: some View {
    HStack(spacing: 8) {
      Button {
        if browser.canGoBack {
          browser.goBack()
        } else {
          browser.returnToOpeningPage()
        }
      } label: {
        Image(systemName: "chevron.left")
      }
      .disabled(!browser.canGoBack && !browser.canReturnToOpeningPage)
      Button(action: browser.goForward) { Image(systemName: "chevron.right") }
        .disabled(!browser.canGoForward)
      Button(action: browser.reload) { Image(systemName: "arrow.clockwise") }
      TextField("https://", text: $browser.addressText)
        .textFieldStyle(.roundedBorder)
        .onSubmit(controller.navigate)
      Button("移動", action: controller.navigate)
        .buttonStyle(.borderedProminent)
      Button(action: controller.toggleBookmark) {
        Image(
          systemName: controller.library.isBookmarked(browser.currentPublicPageURL)
            ? "star.fill" : "star"
        )
      }
      .help("ブックマーク")
      browserLibraryMenu
      if browser.canReturnToOpeningPage {
        Button(action: browser.returnToOpeningPage) {
          Label("元のページ", systemImage: "arrowshape.turn.up.backward")
        }
        .help("別ウインドウを開いた元のページへ戻る")
      }
      if browser.isLoading {
        Button("停止", action: browser.stop)
      }
    }
  }

  private var browserLibraryMenu: some View {
    Menu {
      Section("ブックマーク") {
        if controller.library.bookmarks.isEmpty {
          Text("未登録")
        } else {
          ForEach(controller.library.bookmarks.prefix(20)) { entry in
            Button(entry.title) { controller.open(entry) }
          }
        }
      }
      Section("履歴") {
        if controller.library.history.isEmpty {
          Text("履歴なし")
        } else {
          ForEach(controller.library.history.prefix(20)) { entry in
            Button(entry.title) { controller.open(entry) }
          }
          Divider()
          Button("履歴を消去", role: .destructive) {
            controller.library.clearHistory()
          }
        }
      }
    } label: {
      Image(systemName: "book.closed")
    }
    .help("履歴とブックマーク")
  }

  private var candidateList: some View {
    VStack(alignment: .leading, spacing: 8) {
      HStack {
        Text("検出した配信候補").font(.headline)
        Spacer()
        Button {
          browser.activateInspection()
        } label: {
          Image(systemName: "arrow.triangle.2.circlepath")
        }
        .help("ページを再解析")
      }
      if browser.candidateSummaries.isEmpty {
        ContentUnavailableView(
          "HLS通信を待っています",
          systemImage: "play.rectangle.on.rectangle",
          description: Text("ページ内の動画を再生してください。blob:再生でも元のm3u8応答を監視します。")
        )
      } else {
        List(Array(browser.candidateSummaries.prefix(20))) { candidate in
          VStack(alignment: .leading, spacing: 4) {
            HStack {
              Image(systemName: candidate.isVerified ? "checkmark.seal.fill" : "link")
                .foregroundStyle(candidate.isVerified ? .green : .secondary)
              Text(candidate.sourceLabel).font(.caption.weight(.semibold))
              Spacer()
              Text("深さ \(candidate.frameDepth)")
                .font(.caption2).foregroundStyle(.secondary)
            }
            Text(candidate.url)
              .font(.caption2.monospaced())
              .lineLimit(2)
              .textSelection(.enabled)
            Text(candidate.verificationLabel)
              .font(.caption2)
              .foregroundStyle(.secondary)
          }
          .padding(.vertical, 3)
        }
        .listStyle(.inset)
      }
    }
    .padding(10)
    .frame(maxHeight: .infinity, alignment: .top)
  }
}
